// Generated by gencpp from file ivr_assignment/AnglesStamped.msg
// DO NOT EDIT!


#ifndef IVR_ASSIGNMENT_MESSAGE_ANGLESSTAMPED_H
#define IVR_ASSIGNMENT_MESSAGE_ANGLESSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ivr_assignment/Angles.h>

namespace ivr_assignment
{
template <class ContainerAllocator>
struct AnglesStamped_
{
  typedef AnglesStamped_<ContainerAllocator> Type;

  AnglesStamped_()
    : header()
    , angles()  {
    }
  AnglesStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ivr_assignment::Angles_<ContainerAllocator>  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::ivr_assignment::AnglesStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivr_assignment::AnglesStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AnglesStamped_

typedef ::ivr_assignment::AnglesStamped_<std::allocator<void> > AnglesStamped;

typedef boost::shared_ptr< ::ivr_assignment::AnglesStamped > AnglesStampedPtr;
typedef boost::shared_ptr< ::ivr_assignment::AnglesStamped const> AnglesStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivr_assignment::AnglesStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivr_assignment::AnglesStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::AnglesStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivr_assignment::AnglesStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::AnglesStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivr_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::AnglesStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::AnglesStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::AnglesStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb93e391760e97c458e06a2398a94b44";
  }

  static const char* value(const ::ivr_assignment::AnglesStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb93e391760e97c4ULL;
  static const uint64_t static_value2 = 0x58e06a2398a94b44ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivr_assignment/AnglesStamped";
  }

  static const char* value(const ::ivr_assignment::AnglesStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Joint angles of the robot\n"
"\n"
"Header header\n"
"\n"
"Angles angles\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ivr_assignment/Angles\n"
"# Joint angles of the robot\n"
"\n"
"float64 theta_1 # Yellow joint\n"
"float64 theta_2 # Blue joint (#1)\n"
"float64 theta_3 # Blue joint (#2)\n"
"float64 theta_4 # Green joint\n"
;
  }

  static const char* value(const ::ivr_assignment::AnglesStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnglesStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivr_assignment::AnglesStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivr_assignment::AnglesStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angles: ";
    s << std::endl;
    Printer< ::ivr_assignment::Angles_<ContainerAllocator> >::stream(s, indent + "  ", v.angles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVR_ASSIGNMENT_MESSAGE_ANGLESSTAMPED_H
