// Generated by gencpp from file ivr_assignment/Point.msg
// DO NOT EDIT!


#ifndef IVR_ASSIGNMENT_MESSAGE_POINT_H
#define IVR_ASSIGNMENT_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ivr_assignment
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , hidden(false)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , hidden(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef uint8_t _hidden_type;
  _hidden_type hidden;





  typedef boost::shared_ptr< ::ivr_assignment::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivr_assignment::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::ivr_assignment::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::ivr_assignment::Point > PointPtr;
typedef boost::shared_ptr< ::ivr_assignment::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivr_assignment::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivr_assignment::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivr_assignment::Point_<ContainerAllocator1> & lhs, const ::ivr_assignment::Point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.hidden == rhs.hidden;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivr_assignment::Point_<ContainerAllocator1> & lhs, const ::ivr_assignment::Point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivr_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivr_assignment::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe9f8ba3be526e87aa974f27398bb504";
  }

  static const char* value(const ::ivr_assignment::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe9f8ba3be526e87ULL;
  static const uint64_t static_value2 = 0xaa974f27398bb504ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivr_assignment::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivr_assignment/Point";
  }

  static const char* value(const ::ivr_assignment::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivr_assignment::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Position of object in 3D space\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"bool hidden\n"
;
  }

  static const char* value(const ::ivr_assignment::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivr_assignment::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.hidden);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivr_assignment::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivr_assignment::Point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "hidden: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hidden);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVR_ASSIGNMENT_MESSAGE_POINT_H
