// Generated by gencpp from file ivr_assignment/PointStamped.msg
// DO NOT EDIT!


#ifndef IVR_ASSIGNMENT_MESSAGE_POINTSTAMPED_H
#define IVR_ASSIGNMENT_MESSAGE_POINTSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ivr_assignment/Point.h>

namespace ivr_assignment
{
template <class ContainerAllocator>
struct PointStamped_
{
  typedef PointStamped_<ContainerAllocator> Type;

  PointStamped_()
    : header()
    , point()  {
    }
  PointStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ivr_assignment::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::ivr_assignment::PointStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivr_assignment::PointStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PointStamped_

typedef ::ivr_assignment::PointStamped_<std::allocator<void> > PointStamped;

typedef boost::shared_ptr< ::ivr_assignment::PointStamped > PointStampedPtr;
typedef boost::shared_ptr< ::ivr_assignment::PointStamped const> PointStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivr_assignment::PointStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivr_assignment::PointStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivr_assignment::PointStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::PointStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivr_assignment::PointStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::PointStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivr_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::PointStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::PointStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::PointStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::PointStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::PointStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::PointStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivr_assignment::PointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9a3858b0041bee9fb5e8842c393e941";
  }

  static const char* value(const ::ivr_assignment::PointStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9a3858b0041bee9ULL;
  static const uint64_t static_value2 = 0xfb5e8842c393e941ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivr_assignment::PointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivr_assignment/PointStamped";
  }

  static const char* value(const ::ivr_assignment::PointStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivr_assignment::PointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Position of object in 3D space\n"
"\n"
"Header header\n"
"\n"
"Point point\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ivr_assignment/Point\n"
"# Position of object in 3D space\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"bool hidden\n"
;
  }

  static const char* value(const ::ivr_assignment::PointStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivr_assignment::PointStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivr_assignment::PointStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivr_assignment::PointStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::ivr_assignment::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVR_ASSIGNMENT_MESSAGE_POINTSTAMPED_H
