// Generated by gencpp from file ivr_assignment/StateStamped.msg
// DO NOT EDIT!


#ifndef IVR_ASSIGNMENT_MESSAGE_STATESTAMPED_H
#define IVR_ASSIGNMENT_MESSAGE_STATESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ivr_assignment/State.h>

namespace ivr_assignment
{
template <class ContainerAllocator>
struct StateStamped_
{
  typedef StateStamped_<ContainerAllocator> Type;

  StateStamped_()
    : header()
    , state()  {
    }
  StateStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ivr_assignment::State_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ivr_assignment::StateStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivr_assignment::StateStamped_<ContainerAllocator> const> ConstPtr;

}; // struct StateStamped_

typedef ::ivr_assignment::StateStamped_<std::allocator<void> > StateStamped;

typedef boost::shared_ptr< ::ivr_assignment::StateStamped > StateStampedPtr;
typedef boost::shared_ptr< ::ivr_assignment::StateStamped const> StateStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivr_assignment::StateStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivr_assignment::StateStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivr_assignment::StateStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::StateStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivr_assignment::StateStamped_<ContainerAllocator1> & lhs, const ::ivr_assignment::StateStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivr_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::StateStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivr_assignment::StateStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::StateStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivr_assignment::StateStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::StateStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivr_assignment::StateStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivr_assignment::StateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "112a55435ddc6b46fc7af2d82b7cb445";
  }

  static const char* value(const ::ivr_assignment::StateStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x112a55435ddc6b46ULL;
  static const uint64_t static_value2 = 0xfc7af2d82b7cb445ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivr_assignment::StateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivr_assignment/StateStamped";
  }

  static const char* value(const ::ivr_assignment::StateStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivr_assignment::StateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"\n"
"State state\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ivr_assignment/State\n"
"\n"
"# Joint positions\n"
"Point red\n"
"Point green\n"
"Point blue\n"
"\n"
"# Target positions\n"
"Point sphere\n"
"Point box\n"
"================================================================================\n"
"MSG: ivr_assignment/Point\n"
"# Position of object in 3D space\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"bool hidden\n"
;
  }

  static const char* value(const ::ivr_assignment::StateStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivr_assignment::StateStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivr_assignment::StateStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivr_assignment::StateStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::ivr_assignment::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVR_ASSIGNMENT_MESSAGE_STATESTAMPED_H
