# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ivr_assignment/StateStamped.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ivr_assignment.msg
import std_msgs.msg

class StateStamped(genpy.Message):
  _md5sum = "112a55435ddc6b46fc7af2d82b7cb445"
  _type = "ivr_assignment/StateStamped"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """
Header header

State state
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ivr_assignment/State

# Joint positions
Point red
Point green
Point blue

# Target positions
Point sphere
Point box
================================================================================
MSG: ivr_assignment/Point
# Position of object in 3D space

float64 x
float64 y
float64 z

bool hidden"""
  __slots__ = ['header','state']
  _slot_types = ['std_msgs/Header','ivr_assignment/State']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StateStamped, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = ivr_assignment.msg.State()
    else:
      self.header = std_msgs.msg.Header()
      self.state = ivr_assignment.msg.State()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dB3dB3dB3dB3dB().pack(_x.state.red.x, _x.state.red.y, _x.state.red.z, _x.state.red.hidden, _x.state.green.x, _x.state.green.y, _x.state.green.z, _x.state.green.hidden, _x.state.blue.x, _x.state.blue.y, _x.state.blue.z, _x.state.blue.hidden, _x.state.sphere.x, _x.state.sphere.y, _x.state.sphere.z, _x.state.sphere.hidden, _x.state.box.x, _x.state.box.y, _x.state.box.z, _x.state.box.hidden))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = ivr_assignment.msg.State()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 125
      (_x.state.red.x, _x.state.red.y, _x.state.red.z, _x.state.red.hidden, _x.state.green.x, _x.state.green.y, _x.state.green.z, _x.state.green.hidden, _x.state.blue.x, _x.state.blue.y, _x.state.blue.z, _x.state.blue.hidden, _x.state.sphere.x, _x.state.sphere.y, _x.state.sphere.z, _x.state.sphere.hidden, _x.state.box.x, _x.state.box.y, _x.state.box.z, _x.state.box.hidden,) = _get_struct_3dB3dB3dB3dB3dB().unpack(str[start:end])
      self.state.red.hidden = bool(self.state.red.hidden)
      self.state.green.hidden = bool(self.state.green.hidden)
      self.state.blue.hidden = bool(self.state.blue.hidden)
      self.state.sphere.hidden = bool(self.state.sphere.hidden)
      self.state.box.hidden = bool(self.state.box.hidden)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dB3dB3dB3dB3dB().pack(_x.state.red.x, _x.state.red.y, _x.state.red.z, _x.state.red.hidden, _x.state.green.x, _x.state.green.y, _x.state.green.z, _x.state.green.hidden, _x.state.blue.x, _x.state.blue.y, _x.state.blue.z, _x.state.blue.hidden, _x.state.sphere.x, _x.state.sphere.y, _x.state.sphere.z, _x.state.sphere.hidden, _x.state.box.x, _x.state.box.y, _x.state.box.z, _x.state.box.hidden))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = ivr_assignment.msg.State()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 125
      (_x.state.red.x, _x.state.red.y, _x.state.red.z, _x.state.red.hidden, _x.state.green.x, _x.state.green.y, _x.state.green.z, _x.state.green.hidden, _x.state.blue.x, _x.state.blue.y, _x.state.blue.z, _x.state.blue.hidden, _x.state.sphere.x, _x.state.sphere.y, _x.state.sphere.z, _x.state.sphere.hidden, _x.state.box.x, _x.state.box.y, _x.state.box.z, _x.state.box.hidden,) = _get_struct_3dB3dB3dB3dB3dB().unpack(str[start:end])
      self.state.red.hidden = bool(self.state.red.hidden)
      self.state.green.hidden = bool(self.state.green.hidden)
      self.state.blue.hidden = bool(self.state.blue.hidden)
      self.state.sphere.hidden = bool(self.state.sphere.hidden)
      self.state.box.hidden = bool(self.state.box.hidden)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3dB3dB3dB3dB3dB = None
def _get_struct_3dB3dB3dB3dB3dB():
    global _struct_3dB3dB3dB3dB3dB
    if _struct_3dB3dB3dB3dB3dB is None:
        _struct_3dB3dB3dB3dB3dB = struct.Struct("<3dB3dB3dB3dB3dB")
    return _struct_3dB3dB3dB3dB3dB
